<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ApprovalsSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('approvals')->insert([
            array (
  'id' => 3,
  'institution' => '3',
  'process_name' => 'addBranch',
  'process_description' => 'has added a branch',
  'approval_process_description' => 'has approved addition of a branch',
  'process_code' => '02',
  'process_id' => '3',
  'process_status' => 'Pending',
  'user_id' => '1',
  'approver_id' => NULL,
  'team_id' => '3',
  'edit_package' => '',
  'clearance' => NULL,
  'updated_at' => '2023-07-01 14:09:14',
  'created_at' => '2023-07-01 14:09:14',
  'approval_status' => NULL,
  'reset_email' => NULL,
),
            array (
  'id' => 4,
  'institution' => '4',
  'process_name' => 'addBranch',
  'process_description' => 'has added a branch',
  'approval_process_description' => 'has approved addition of a branch',
  'process_code' => '02',
  'process_id' => '4',
  'process_status' => 'Pending',
  'user_id' => '1',
  'approver_id' => NULL,
  'team_id' => '4',
  'edit_package' => '',
  'clearance' => NULL,
  'updated_at' => '2023-07-01 14:17:40',
  'created_at' => '2023-07-01 14:17:40',
  'approval_status' => NULL,
  'reset_email' => NULL,
),
            array (
  'id' => 799,
  'institution' => '18',
  'process_name' => 'Register_stock',
  'process_description' => 'ADMIN has registered new stock of Cocoa',
  'approval_process_description' => 'has approved a registration',
  'process_code' => '102',
  'process_id' => '18',
  'process_status' => 'APPROVED',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '18',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => NULL,
  'created_at' => NULL,
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 800,
  'institution' => '19',
  'process_name' => 'Register_stock',
  'process_description' => 'ADMIN has registered new stock of Maize',
  'approval_process_description' => 'has approved a registration',
  'process_code' => '102',
  'process_id' => '19',
  'process_status' => 'APPROVED',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '19',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => NULL,
  'created_at' => NULL,
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 801,
  'institution' => '20',
  'process_name' => 'Register_stock',
  'process_description' => 'ADMIN has registered new stock of Sesame',
  'approval_process_description' => 'has approved a registration',
  'process_code' => '102',
  'process_id' => '20',
  'process_status' => 'APPROVED',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '20',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => NULL,
  'created_at' => NULL,
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 802,
  'institution' => '21',
  'process_name' => 'Register_stock',
  'process_description' => 'ADMIN has registered new stock of Maize',
  'approval_process_description' => 'has approved a registration',
  'process_code' => '102',
  'process_id' => '21',
  'process_status' => 'APPROVED',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '21',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => NULL,
  'created_at' => NULL,
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 803,
  'institution' => '',
  'process_name' => 'passwordPolicy',
  'process_description' => 'ADMIN has  requested  to  change password policy ',
  'approval_process_description' => '{"length":"8","requireUppercase":"1","requireNumeric":"1","requireSpecialCharacter":"1","limiter":5,"passwordExpire":"30"}',
  'process_code' => '30',
  'process_id' => '1',
  'process_status' => 'PENDING',
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-03-08 13:33:14',
  'created_at' => '2024-03-08 13:33:14',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 804,
  'institution' => '22',
  'process_name' => 'Register_stock',
  'process_description' => 'ADMIN has registered new stock of Cashew Nuts',
  'approval_process_description' => 'has approved a registration',
  'process_code' => '102',
  'process_id' => '22',
  'process_status' => 'APPROVED',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '22',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => NULL,
  'created_at' => NULL,
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 805,
  'institution' => '24',
  'process_name' => 'stock Release',
  'process_description' => 'ADMIN has registered stock release  forPeter Peter',
  'approval_process_description' => NULL,
  'process_code' => '103',
  'process_id' => '24',
  'process_status' => NULL,
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '24',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => NULL,
  'created_at' => NULL,
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 806,
  'institution' => '23',
  'process_name' => 'stock Release',
  'process_description' => 'ADMIN has registered stock release  for Peter Peter',
  'approval_process_description' => NULL,
  'process_code' => '103',
  'process_id' => '23',
  'process_status' => NULL,
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '23',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-03-11 15:18:09',
  'created_at' => '2024-03-11 15:18:09',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 807,
  'institution' => '22',
  'process_name' => 'stock Release',
  'process_description' => 'ADMIN has registered stock release  for Andrew Andrew',
  'approval_process_description' => NULL,
  'process_code' => '103',
  'process_id' => '22',
  'process_status' => NULL,
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '22',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-03-11 16:17:19',
  'created_at' => '2024-03-11 16:17:19',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 808,
  'institution' => '23',
  'process_name' => 'Register_stock',
  'process_description' => 'ADMIN has registered new stock of Sesame',
  'approval_process_description' => 'has approved a registration',
  'process_code' => '102',
  'process_id' => '23',
  'process_status' => 'APPROVED',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '23',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-03-11 16:46:34',
  'created_at' => '2024-03-11 16:46:34',
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 809,
  'institution' => '22',
  'process_name' => 'stock Release',
  'process_description' => 'ADMIN has registered stock release  for Neema Neema',
  'approval_process_description' => NULL,
  'process_code' => '103',
  'process_id' => '22',
  'process_status' => NULL,
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '22',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-03-11 17:14:53',
  'created_at' => '2024-03-11 17:14:53',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 810,
  'institution' => '24',
  'process_name' => 'Register_stock',
  'process_description' => 'ADMIN has registered new stock of Red Beans',
  'approval_process_description' => 'has approved a registration',
  'process_code' => '102',
  'process_id' => '24',
  'process_status' => 'APPROVED',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '24',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-03-11 17:19:45',
  'created_at' => '2024-03-11 17:19:45',
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 811,
  'institution' => '25',
  'process_name' => 'Register_stock',
  'process_description' => 'ADMIN has registered new stock of Red Beans',
  'approval_process_description' => 'has approved a registration',
  'process_code' => '102',
  'process_id' => '25',
  'process_status' => 'APPROVED',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '25',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-03-11 17:22:24',
  'created_at' => '2024-03-11 17:22:24',
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 812,
  'institution' => '26',
  'process_name' => 'Register_stock',
  'process_description' => 'ADMIN has registered new stock of Sorghum',
  'approval_process_description' => 'has approved a registration',
  'process_code' => '102',
  'process_id' => '26',
  'process_status' => 'APPROVED',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '26',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-03-12 08:51:33',
  'created_at' => '2024-03-12 08:51:33',
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 813,
  'institution' => '26',
  'process_name' => 'stock Release',
  'process_description' => 'ADMIN has registered stock release  for Neema Neema',
  'approval_process_description' => NULL,
  'process_code' => '103',
  'process_id' => '26',
  'process_status' => 'APPROVED',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '26',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-03-12 08:52:08',
  'created_at' => '2024-03-12 08:52:08',
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 814,
  'institution' => '27',
  'process_name' => 'Register_stock',
  'process_description' => 'PECY has registered new stock of Cotton',
  'approval_process_description' => 'has approved a registration',
  'process_code' => '102',
  'process_id' => '27',
  'process_status' => 'APPROVED',
  'user_id' => '50',
  'approver_id' => '50',
  'team_id' => '27',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-03-12 12:15:51',
  'created_at' => '2024-03-12 12:15:51',
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 815,
  'institution' => '28',
  'process_name' => 'Register_stock',
  'process_description' => 'PECY has registered new stock of Coffee',
  'approval_process_description' => 'has approved a registration',
  'process_code' => '102',
  'process_id' => '28',
  'process_status' => 'APPROVED',
  'user_id' => '50',
  'approver_id' => '50',
  'team_id' => '28',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-03-12 14:51:05',
  'created_at' => '2024-03-12 14:51:05',
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 816,
  'institution' => '29',
  'process_name' => 'Register_stock',
  'process_description' => 'ADMIN has registered new stock of Sugar Beans',
  'approval_process_description' => 'has approved a registration',
  'process_code' => '102',
  'process_id' => '29',
  'process_status' => 'APPROVED',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '29',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-03-15 13:59:08',
  'created_at' => '2024-03-15 13:59:08',
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 817,
  'institution' => '30',
  'process_name' => 'Register_stock',
  'process_description' => 'ADMIN has registered new stock of Cotton',
  'approval_process_description' => 'has approved a registration',
  'process_code' => '102',
  'process_id' => '30',
  'process_status' => 'APPROVED',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '30',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-03-19 17:59:29',
  'created_at' => '2024-03-19 17:59:29',
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 818,
  'institution' => '31',
  'process_name' => 'Register_stock',
  'process_description' => 'ADMIN has registered new stock of Red Beans',
  'approval_process_description' => 'has approved a registration',
  'process_code' => '102',
  'process_id' => '31',
  'process_status' => 'APPROVED',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '31',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-03-24 11:05:34',
  'created_at' => '2024-03-24 11:05:34',
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 819,
  'institution' => ' ',
  'process_name' => 'editRole',
  'process_description' => 'ADMIN has edited role named - ADMINISTRATOR',
  'approval_process_description' => 'ADMIN has edited role named - ADMINISTRATOR',
  'process_code' => '24',
  'process_id' => '16',
  'process_status' => 'Pending',
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '',
  'edit_package' => '{"department_name":"ADMINISTRATOR","description":"Second administrator","permissions":"{\\"0\\":\\"2\\",\\"1\\":\\"3\\",\\"2\\":\\"4\\",\\"3\\":\\"5\\",\\"4\\":\\"6\\",\\"5\\":\\"7\\",\\"6\\":\\"8\\",\\"7\\":\\"9\\",\\"8\\":\\"10\\",\\"9\\":\\"11\\",\\"10\\":\\"12\\",\\"11\\":\\"13\\",\\"12\\":\\"14\\",\\"13\\":\\"15\\",\\"14\\":\\"16\\",\\"15\\":\\"17\\",\\"17\\":\\"17\\",\\"18\\":\\"18\\",\\"20\\":\\"20\\",\\"21\\":\\"21\\",\\"22\\":\\"22\\",\\"24\\":\\"24\\",\\"25\\":\\"25\\",\\"26\\":\\"26\\",\\"28\\":\\"28\\",\\"30\\":\\"30\\",\\"34\\":\\"34\\",\\"38\\":\\"38\\",\\"42\\":\\"42\\"}","modules":"{\\"0\\":\\"2\\",\\"1\\":\\"3\\",\\"2\\":\\"4\\",\\"3\\":\\"5\\",\\"4\\":\\"6\\",\\"5\\":\\"7\\",\\"6\\":\\"8\\",\\"7\\":\\"9\\",\\"8\\":\\"10\\",\\"9\\":\\"11\\",\\"10\\":\\"12\\",\\"11\\":\\"13\\",\\"12\\":\\"14\\",\\"13\\":\\"15\\",\\"14\\":\\"16\\",\\"15\\":\\"17\\",\\"17\\":\\"17\\",\\"18\\":\\"18\\",\\"20\\":\\"20\\",\\"21\\":\\"21\\",\\"22\\":\\"22\\",\\"24\\":\\"24\\",\\"25\\":\\"25\\",\\"26\\":\\"26\\",\\"28\\":\\"28\\",\\"30\\":\\"30\\",\\"34\\":\\"34\\",\\"38\\":\\"38\\",\\"42\\":\\"42\\"}","status":"ACTIVE"}',
  'clearance' => NULL,
  'updated_at' => '2024-07-17 11:32:37',
  'created_at' => '2024-07-17 11:32:37',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 820,
  'institution' => ' ',
  'process_name' => 'addRole',
  'process_description' => 'ADMIN has edited role named - TEST RUN',
  'approval_process_description' => ' has approved creation of a new role',
  'process_code' => '24',
  'process_id' => '17',
  'process_status' => 'APPROVED',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-18 07:40:48',
  'created_at' => '2024-07-17 12:55:40',
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 821,
  'institution' => ' ',
  'process_name' => 'editRole',
  'process_description' => 'ADMIN has edited role named - TEST RUN',
  'approval_process_description' => 'ADMIN has edited role named - TEST RUN',
  'process_code' => '24',
  'process_id' => '17',
  'process_status' => 'PENDING',
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '',
  'edit_package' => '{"status":"BLOCK"}',
  'clearance' => NULL,
  'updated_at' => '2024-07-18 06:17:51',
  'created_at' => '2024-07-18 05:12:07',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 822,
  'institution' => ' ',
  'process_name' => 'addRole',
  'process_description' => 'ADMIN has edited role named - TEST ROLE',
  'approval_process_description' => ' has approved creation of a new role',
  'process_code' => '24',
  'process_id' => '18',
  'process_status' => 'APPROVED',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-18 07:40:38',
  'created_at' => '2024-07-18 07:31:17',
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 823,
  'institution' => ' ',
  'process_name' => 'addRole',
  'process_description' => 'ADMIN has edited role named - THE ROLE',
  'approval_process_description' => ' has approved creation of a new role',
  'process_code' => '24',
  'process_id' => '19',
  'process_status' => 'APPROVED',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-18 07:40:35',
  'created_at' => '2024-07-18 07:37:21',
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 824,
  'institution' => ' ',
  'process_name' => 'editRole',
  'process_description' => 'ADMIN has edited role named - TEST MO',
  'approval_process_description' => 'Approved editing of the node',
  'process_code' => '24',
  'process_id' => '15',
  'process_status' => 'PENDING',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '',
  'edit_package' => '{"department_name":"TEST MO","description":"TEST MOZ","permissions":"{\\"1\\":\\"1\\",\\"3\\":\\"3\\",\\"6\\":\\"6\\",\\"7\\":\\"7\\",\\"10\\":\\"10\\",\\"11\\":\\"11\\",\\"12\\":\\"12\\",\\"14\\":\\"14\\",\\"18\\":\\"18\\",\\"19\\":\\"19\\"}","modules":"{\\"1\\":\\"1\\",\\"3\\":\\"3\\",\\"6\\":\\"6\\",\\"7\\":\\"7\\",\\"10\\":\\"10\\",\\"11\\":\\"11\\",\\"12\\":\\"12\\",\\"14\\":\\"14\\",\\"18\\":\\"18\\",\\"19\\":\\"19\\"}","status":"ACTIVE"}',
  'clearance' => NULL,
  'updated_at' => '2024-07-18 07:55:59',
  'created_at' => '2024-07-18 07:48:03',
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 825,
  'institution' => ' ',
  'process_name' => 'editRole',
  'process_description' => 'ADMIN has edited role named - ADMINISTRATOR',
  'approval_process_description' => 'Approved editing of the node',
  'process_code' => '24',
  'process_id' => '10',
  'process_status' => 'PENDING',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '',
  'edit_package' => '{"department_name":"ADMINISTRATOR","description":"Dicta eum voluptatib","permissions":"[\\"2\\",false,false,false,false,\\"5\\",false,\\"7\\",false,\\"9\\",\\"10\\",false,false,\\"13\\",\\"14\\",false,false,\\"17\\",\\"18\\",\\"19\\",\\"20\\",false,false,\\"23\\",\\"24\\",\\"25\\",\\"26\\",\\"27\\",\\"28\\",false,\\"30\\",\\"31\\",\\"32\\",false,false,\\"35\\",\\"36\\",false,false,false,\\"40\\",\\"41\\",\\"42\\",\\"43\\",\\"44\\",\\"45\\",\\"46\\"]","modules":"[\\"2\\",false,false,false,false,\\"5\\",false,\\"7\\",false,\\"9\\",\\"10\\",false,false,\\"13\\",\\"14\\",false,false,\\"17\\",\\"18\\",\\"19\\",\\"20\\",false,false,\\"23\\",\\"24\\",\\"25\\",\\"26\\",\\"27\\",\\"28\\",false,\\"30\\",\\"31\\",\\"32\\",false,false,\\"35\\",\\"36\\",false,false,false,\\"40\\",\\"41\\",\\"42\\",\\"43\\",\\"44\\",\\"45\\",\\"46\\"]","status":"ACTIVE"}',
  'clearance' => NULL,
  'updated_at' => '2024-07-18 08:28:35',
  'created_at' => '2024-07-18 07:56:47',
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 826,
  'institution' => ' ',
  'process_name' => 'addCommodity',
  'process_description' => 'ADMIN has added a role named - test7',
  'approval_process_description' => ' has approved creation of a new role',
  'process_code' => '24',
  'process_id' => '19',
  'process_status' => 'APPROVED',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-18 10:36:43',
  'created_at' => '2024-07-18 10:32:11',
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 827,
  'institution' => ' ',
  'process_name' => 'changePrice',
  'process_description' => 'ADMIN has changed the price per kilo of commodity named  - Maize, from 8000 to 790',
  'approval_process_description' => 'ADMIN has edited role named - Maize',
  'process_code' => '24',
  'process_id' => '1',
  'process_status' => 'PENDING',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '',
  'edit_package' => '{"price_per_kilo":790}',
  'clearance' => NULL,
  'updated_at' => '2024-07-29 07:35:29',
  'created_at' => '2024-07-19 06:26:09',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 828,
  'institution' => ' ',
  'process_name' => 'changePrice',
  'process_description' => 'ADMIN has changed the price per kilo of commodity named  - Cotton, from 1200 to 8000',
  'approval_process_description' => 'Approved change of price',
  'process_code' => '24',
  'process_id' => '2',
  'process_status' => 'PENDING',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '',
  'edit_package' => '{"price_per_kilo":8000}',
  'clearance' => NULL,
  'updated_at' => '2024-07-22 17:50:55',
  'created_at' => '2024-07-19 06:45:11',
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 829,
  'institution' => ' ',
  'process_name' => 'addBranch',
  'process_description' => 'ADMIN has added a branch named - Test 1',
  'approval_process_description' => 'ADMIN has added a branch named - Test 1',
  'process_code' => '24',
  'process_id' => '33',
  'process_status' => 'PENDING',
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-19 12:40:39',
  'created_at' => '2024-07-19 12:40:39',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 830,
  'institution' => '32',
  'process_name' => 'Register_stock',
  'process_description' => 'ADMIN has registered new stock of Cocoa',
  'approval_process_description' => 'has approved a registration',
  'process_code' => '102',
  'process_id' => '32',
  'process_status' => 'APPROVED',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '32',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-21 11:47:09',
  'created_at' => '2024-07-21 11:47:09',
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 831,
  'institution' => '33',
  'process_name' => 'Register_stock',
  'process_description' => 'ADMIN has registered new stock of Cocoa',
  'approval_process_description' => 'has approved a registration',
  'process_code' => '102',
  'process_id' => '33',
  'process_status' => 'APPROVED',
  'user_id' => '32',
  'approver_id' => '32',
  'team_id' => '33',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-21 11:47:54',
  'created_at' => '2024-07-21 11:47:54',
  'approval_status' => 'APPROVED',
  'reset_email' => NULL,
),
            array (
  'id' => 832,
  'institution' => ' ',
  'process_name' => 'registerStock',
  'process_description' => 'Collateral Manager - ADMIN has registered new stock of Sesame',
  'approval_process_description' => 'has approved this action',
  'process_code' => '24',
  'process_id' => '34',
  'process_status' => 'PENDING',
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-21 09:05:27',
  'created_at' => '2024-07-21 09:05:27',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 833,
  'institution' => ' ',
  'process_name' => 'registerStock',
  'process_description' => 'Collateral Manager - ADMIN has registered new stock of Maize',
  'approval_process_description' => 'has approved this action',
  'process_code' => '24',
  'process_id' => '35',
  'process_status' => 'PENDING',
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-21 09:11:43',
  'created_at' => '2024-07-21 09:11:43',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 834,
  'institution' => ' ',
  'process_name' => 'registerStock',
  'process_description' => 'Collateral Manager - ADMIN has registered new stock of Mogas gasoline',
  'approval_process_description' => 'has approved this action',
  'process_code' => '24',
  'process_id' => '36',
  'process_status' => 'PENDING',
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-21 09:21:59',
  'created_at' => '2024-07-21 09:21:59',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 835,
  'institution' => ' ',
  'process_name' => 'registerStock',
  'process_description' => 'Collateral Manager - ADMIN has registered new stock of Cotton',
  'approval_process_description' => 'has approved this action',
  'process_code' => '24',
  'process_id' => '37',
  'process_status' => 'PENDING',
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-21 09:31:49',
  'created_at' => '2024-07-21 09:31:49',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 836,
  'institution' => ' ',
  'process_name' => 'registerStock',
  'process_description' => 'Collateral Manager - ADMIN has registered new stock of Cocoa',
  'approval_process_description' => 'has approved this action',
  'process_code' => '24',
  'process_id' => '38',
  'process_status' => 'PENDING',
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-21 09:32:09',
  'created_at' => '2024-07-21 09:32:09',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 837,
  'institution' => ' ',
  'process_name' => 'registerStock',
  'process_description' => 'Collateral Manager - ADMIN has registered new stock of Petrol',
  'approval_process_description' => 'has approved this action',
  'process_code' => '24',
  'process_id' => '39',
  'process_status' => 'PENDING',
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-21 09:32:29',
  'created_at' => '2024-07-21 09:32:29',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 838,
  'institution' => ' ',
  'process_name' => 'registerStock',
  'process_description' => 'Collateral Manager - ADMIN has registered new stock of Cocoa',
  'approval_process_description' => 'has approved this action',
  'process_code' => '24',
  'process_id' => '40',
  'process_status' => 'PENDING',
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-22 18:05:12',
  'created_at' => '2024-07-22 18:05:12',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 839,
  'institution' => ' ',
  'process_name' => 'registerStock',
  'process_description' => 'Collateral Manager - ADMIN has registered new stock of Petrol',
  'approval_process_description' => 'has approved this action',
  'process_code' => '24',
  'process_id' => '41',
  'process_status' => 'PENDING',
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-22 18:07:51',
  'created_at' => '2024-07-22 18:07:51',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 840,
  'institution' => '29',
  'process_name' => 'stock Release',
  'process_description' => 'ADMIN has registered stock release  for Andrew Andrew',
  'approval_process_description' => NULL,
  'process_code' => '103',
  'process_id' => '29',
  'process_status' => NULL,
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '29',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-23 00:40:04',
  'created_at' => '2024-07-23 00:40:04',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 841,
  'institution' => ' ',
  'process_name' => 'registerStock',
  'process_description' => 'Collateral Manager - ADMIN has registered new stock of Cotton',
  'approval_process_description' => 'has approved this action',
  'process_code' => '24',
  'process_id' => '42',
  'process_status' => 'PENDING',
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-28 19:35:32',
  'created_at' => '2024-07-28 19:35:32',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 842,
  'institution' => ' ',
  'process_name' => 'registerStock',
  'process_description' => 'Collateral Manager - ADMIN has registered new stock of Maize',
  'approval_process_description' => 'has approved this action',
  'process_code' => '24',
  'process_id' => '43',
  'process_status' => 'PENDING',
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-28 20:09:39',
  'created_at' => '2024-07-28 20:09:39',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 843,
  'institution' => ' ',
  'process_name' => 'registerStock',
  'process_description' => 'Collateral Manager - Omnis quo repudianda has registered new stock of Cashew Nuts',
  'approval_process_description' => 'has approved this action',
  'process_code' => '24',
  'process_id' => '44',
  'process_status' => 'PENDING',
  'user_id' => '60',
  'approver_id' => NULL,
  'team_id' => '',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-29 03:29:16',
  'created_at' => '2024-07-29 03:29:16',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 844,
  'institution' => '36',
  'process_name' => 'stock Release',
  'process_description' => 'ADMIN has registered stock release  for Enim Enim',
  'approval_process_description' => NULL,
  'process_code' => '103',
  'process_id' => '36',
  'process_status' => NULL,
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '36',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-29 08:59:41',
  'created_at' => '2024-07-29 08:59:41',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 845,
  'institution' => '35',
  'process_name' => 'stock Release',
  'process_description' => 'ADMIN has registered stock release  for Andrew Andrew',
  'approval_process_description' => NULL,
  'process_code' => '103',
  'process_id' => '35',
  'process_status' => NULL,
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '35',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-29 09:08:52',
  'created_at' => '2024-07-29 09:08:52',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 846,
  'institution' => '37',
  'process_name' => 'stock Release',
  'process_description' => 'ADMIN has registered stock release  for Andrew Andrew',
  'approval_process_description' => NULL,
  'process_code' => '103',
  'process_id' => '37',
  'process_status' => NULL,
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '37',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-29 09:12:05',
  'created_at' => '2024-07-29 09:12:05',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 847,
  'institution' => '38',
  'process_name' => 'stock Release',
  'process_description' => 'ADMIN has registered stock release  for Andrew Andrew',
  'approval_process_description' => NULL,
  'process_code' => '103',
  'process_id' => '38',
  'process_status' => NULL,
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '38',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-29 09:29:57',
  'created_at' => '2024-07-29 09:29:57',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 848,
  'institution' => ' ',
  'process_name' => 'registerStock',
  'process_description' => 'Collateral Manager - ADMIN has registered new stock of Cotton',
  'approval_process_description' => 'has approved this action',
  'process_code' => '24',
  'process_id' => '45',
  'process_status' => 'PENDING',
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-29 07:29:31',
  'created_at' => '2024-07-29 07:29:31',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 849,
  'institution' => ' ',
  'process_name' => 'registerStock',
  'process_description' => 'Collateral Manager - ADMIN has registered new stock of Diesel',
  'approval_process_description' => 'has approved this action',
  'process_code' => '24',
  'process_id' => '46',
  'process_status' => 'PENDING',
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-29 07:29:54',
  'created_at' => '2024-07-29 07:29:54',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 850,
  'institution' => ' ',
  'process_name' => 'registerStock',
  'process_description' => 'Collateral Manager - ADMIN has registered new stock of Cotton',
  'approval_process_description' => 'has approved this action',
  'process_code' => '24',
  'process_id' => '47',
  'process_status' => 'PENDING',
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-29 07:32:36',
  'created_at' => '2024-07-29 07:32:36',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
),
            array (
  'id' => 851,
  'institution' => '39',
  'process_name' => 'stock Release',
  'process_description' => 'ADMIN has registered stock release  for Andrew Andrew',
  'approval_process_description' => NULL,
  'process_code' => '103',
  'process_id' => '39',
  'process_status' => NULL,
  'user_id' => '32',
  'approver_id' => NULL,
  'team_id' => '39',
  'edit_package' => NULL,
  'clearance' => NULL,
  'updated_at' => '2024-07-29 10:48:44',
  'created_at' => '2024-07-29 10:48:44',
  'approval_status' => 'PENDING',
  'reset_email' => NULL,
)
        ]);
    }
}