<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BranchesSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('branches')->insert([
            array (
  'id' => 12,
  'institution_id' => NULL,
  'name' => 'MAFINGA DC BRANCH',
  'region' => 'IRINGA',
  'ward' => 'MAFINGA',
  'district' => NULL,
  'branchNumber' => '9010',
  'parentBranch' => NULL,
  'monthly_disbursement_amount' => NULL,
  'amount_owed' => NULL,
  'phone_number' => NULL,
  'email' => 'ema@gmail.com',
  'automatic_payments' => NULL,
  'branch_status' => 'PENDING',
  'Status' => NULL,
  'selected' => 0,
  'created_at' => '2023-07-02 22:48:14',
  'updated_at' => '2023-07-02 22:48:14',
),
            array (
  'id' => 17,
  'institution_id' => NULL,
  'name' => 'SOWETO',
  'region' => 'DAR ES SALAAM ',
  'ward' => 'ILALA',
  'district' => NULL,
  'branchNumber' => '9583',
  'parentBranch' => NULL,
  'monthly_disbursement_amount' => NULL,
  'amount_owed' => NULL,
  'phone_number' => '0624451311',
  'email' => 'ema@gmail.com',
  'automatic_payments' => NULL,
  'branch_status' => 'ACTIVE',
  'Status' => NULL,
  'selected' => 0,
  'created_at' => '2023-07-03 11:37:35',
  'updated_at' => '2023-07-03 11:37:35',
),
            array (
  'id' => 25,
  'institution_id' => NULL,
  'name' => 'HQ',
  'region' => 'DAR ES SALAAM',
  'ward' => 'KINONDONI',
  'district' => NULL,
  'branchNumber' => '9307',
  'parentBranch' => NULL,
  'monthly_disbursement_amount' => NULL,
  'amount_owed' => NULL,
  'phone_number' => '0624531123',
  'email' => 'makongosaccos@gmail.com',
  'automatic_payments' => NULL,
  'branch_status' => 'PENDING',
  'Status' => NULL,
  'selected' => 0,
  'created_at' => '2023-08-02 06:50:44',
  'updated_at' => '2023-08-02 06:50:44',
),
            array (
  'id' => 30,
  'institution_id' => '8',
  'name' => 'text',
  'region' => 'mwanza ',
  'ward' => 'mjini',
  'district' => NULL,
  'branchNumber' => '9308',
  'parentBranch' => NULL,
  'monthly_disbursement_amount' => NULL,
  'amount_owed' => NULL,
  'phone_number' => '7777777777',
  'email' => 'mwana@gmail.com',
  'automatic_payments' => NULL,
  'branch_status' => 'ACTIVE',
  'Status' => NULL,
  'selected' => 0,
  'created_at' => '2023-11-20 12:30:18',
  'updated_at' => '2023-11-20 12:33:10',
),
            array (
  'id' => 31,
  'institution_id' => '8',
  'name' => 'demo',
  'region' => 'DAR ES SALAAM ',
  'ward' => 'MADABA',
  'district' => NULL,
  'branchNumber' => '9309',
  'parentBranch' => NULL,
  'monthly_disbursement_amount' => NULL,
  'amount_owed' => NULL,
  'phone_number' => '+2551234567891',
  'email' => 'mwana@gmail.com',
  'automatic_payments' => NULL,
  'branch_status' => 'PENDING',
  'Status' => NULL,
  'selected' => 0,
  'created_at' => '2023-11-24 13:33:33',
  'updated_at' => '2023-11-24 13:33:33',
),
            array (
  'id' => 32,
  'institution_id' => NULL,
  'name' => 'Test 1',
  'region' => '10',
  'ward' => '617',
  'district' => '60',
  'branchNumber' => NULL,
  'parentBranch' => NULL,
  'monthly_disbursement_amount' => NULL,
  'amount_owed' => NULL,
  'phone_number' => 'Sed quis qui rerum s',
  'email' => 'gevix@mailinator.com',
  'automatic_payments' => NULL,
  'branch_status' => NULL,
  'Status' => 'PENDING',
  'selected' => 0,
  'created_at' => '2024-07-19 12:39:47',
  'updated_at' => '2024-07-19 12:39:47',
),
            array (
  'id' => 33,
  'institution_id' => NULL,
  'name' => 'Test 1',
  'region' => '10',
  'ward' => '617',
  'district' => '60',
  'branchNumber' => NULL,
  'parentBranch' => NULL,
  'monthly_disbursement_amount' => NULL,
  'amount_owed' => NULL,
  'phone_number' => 'Sed quis qui rerum s',
  'email' => 'gevix@mailinator.com',
  'automatic_payments' => NULL,
  'branch_status' => NULL,
  'Status' => 'PENDING',
  'selected' => 0,
  'created_at' => '2024-07-19 12:40:39',
  'updated_at' => '2024-07-19 12:40:39',
)
        ]);
    }
}