<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FarmersSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('farmers')->insert([
            array (
  'id' => 18,
  'first_name' => 'Andrew',
  'last_name' => 'Mashamba',
  'date_of_birth' => '1985-05-17',
  'gender' => 'Male',
  'contact_number' => NULL,
  'email' => 'andrew.s.mashamba@gmail.com',
  'address' => 'Namanga Rd',
  'occupation' => NULL,
  'education_level' => NULL,
  'marital_status' => 'Married',
  'dependent_count' => NULL,
  'annual_income' => NULL,
  'City' => NULL,
  'phone_number' => NULL,
  'Status' => 'ACTIVE',
  'created_at' => '2024-07-28 15:03:32',
  'updated_at' => '2024-07-29 00:53:49',
  'collateral_manager_id' => 23,
  'identificationType' => 'NIDA',
  'identificationNo' => '11101010101010',
  'region' => '16',
  'district' => '105',
  'ward' => '1572',
  'branch' => 25,
  'process' => '14',
  'step' => '3',
  'xx' => NULL,
),
            array (
  'id' => 19,
  'first_name' => 'Enim',
  'last_name' => 'Saepe ',
  'date_of_birth' => '2013-09-13',
  'gender' => 'Male',
  'contact_number' => NULL,
  'email' => 'andrew.s.mashamba@gmail.com',
  'address' => 'Namanga Rd',
  'occupation' => NULL,
  'education_level' => NULL,
  'marital_status' => 'Married',
  'dependent_count' => NULL,
  'annual_income' => NULL,
  'City' => NULL,
  'phone_number' => NULL,
  'Status' => 'ACTIVE',
  'created_at' => '2024-07-28 22:05:51',
  'updated_at' => '2024-07-29 02:02:41',
  'collateral_manager_id' => 23,
  'identificationType' => 'Voter-ID',
  'identificationNo' => '45676767687',
  'region' => '14',
  'district' => '90',
  'ward' => '588',
  'branch' => 25,
  'process' => '14',
  'step' => '3',
  'xx' => NULL,
),
            array (
  'id' => 20,
  'first_name' => 'Velit ',
  'last_name' => 'Dolorum ',
  'date_of_birth' => '2008-11-17',
  'gender' => 'Male',
  'contact_number' => NULL,
  'email' => 'andrew.s.mashamba@gmail.com',
  'address' => 'Namanga Rd',
  'occupation' => NULL,
  'education_level' => NULL,
  'marital_status' => 'Married',
  'dependent_count' => NULL,
  'annual_income' => NULL,
  'City' => NULL,
  'phone_number' => NULL,
  'Status' => 'ACTIVE',
  'created_at' => '2024-07-28 22:14:35',
  'updated_at' => '2024-07-29 06:56:36',
  'collateral_manager_id' => 23,
  'identificationType' => 'Voter-ID',
  'identificationNo' => 'Nisi et corporis est',
  'region' => '10',
  'district' => '63',
  'ward' => '746',
  'branch' => 25,
  'process' => '14',
  'step' => '3',
  'xx' => NULL,
),
            array (
  'id' => 21,
  'first_name' => 'Distinctio',
  'last_name' => 'Nihil',
  'date_of_birth' => '1993-12-22',
  'gender' => 'Male',
  'contact_number' => NULL,
  'email' => 'masik@mailinator.com',
  'address' => 'Sint aperiam id qui ',
  'occupation' => NULL,
  'education_level' => NULL,
  'marital_status' => 'Single',
  'dependent_count' => NULL,
  'annual_income' => NULL,
  'City' => NULL,
  'phone_number' => NULL,
  'Status' => 'PENDING',
  'created_at' => '2024-07-29 01:22:12',
  'updated_at' => '2024-07-29 01:22:12',
  'collateral_manager_id' => 23,
  'identificationType' => 'NIDA',
  'identificationNo' => 'Obcaecati omnis quae',
  'region' => '8',
  'district' => '42',
  'ward' => '1436',
  'branch' => 25,
  'process' => '114',
  'step' => '2',
  'xx' => NULL,
),
            array (
  'id' => 22,
  'first_name' => 'Aberspiciatis',
  'last_name' => 'Enim ',
  'date_of_birth' => '2009-01-17',
  'gender' => 'Male',
  'contact_number' => NULL,
  'email' => 'mukit@mailinator.com',
  'address' => 'Ex unde veniam labo',
  'occupation' => NULL,
  'education_level' => NULL,
  'marital_status' => 'Divorced',
  'dependent_count' => NULL,
  'annual_income' => NULL,
  'City' => NULL,
  'phone_number' => NULL,
  'Status' => 'SUSPENDED',
  'created_at' => '2024-07-29 01:33:26',
  'updated_at' => '2024-07-29 02:03:48',
  'collateral_manager_id' => 23,
  'identificationType' => 'NIDA',
  'identificationNo' => 'Et adipisci velit q',
  'region' => '24',
  'district' => '139',
  'ward' => '1130',
  'branch' => 25,
  'process' => '14',
  'step' => '2',
  'xx' => NULL,
),
            array (
  'id' => 23,
  'first_name' => 'Ducimus',
  'last_name' => 'Animi',
  'date_of_birth' => '1985-07-16',
  'gender' => 'Male',
  'contact_number' => NULL,
  'email' => 'mawenegyc@mailinator.com',
  'address' => 'Corporis occaecat ar',
  'occupation' => NULL,
  'education_level' => NULL,
  'marital_status' => 'Married',
  'dependent_count' => NULL,
  'annual_income' => NULL,
  'City' => NULL,
  'phone_number' => NULL,
  'Status' => 'SUSPENDED',
  'created_at' => '2024-07-29 01:40:29',
  'updated_at' => '2024-07-29 02:03:42',
  'collateral_manager_id' => 23,
  'identificationType' => 'NIDA',
  'identificationNo' => 'Ea dolor recusandae',
  'region' => '15',
  'district' => '100',
  'ward' => '863',
  'branch' => 25,
  'process' => '14',
  'step' => '2',
  'xx' => NULL,
),
            array (
  'id' => 24,
  'first_name' => 'Necessitatibus',
  'last_name' => 'Non',
  'date_of_birth' => '1977-09-25',
  'gender' => 'Male',
  'contact_number' => NULL,
  'email' => 'pilaziqiso@mailinator.com',
  'address' => 'Excepteur aliquid eu',
  'occupation' => NULL,
  'education_level' => NULL,
  'marital_status' => 'Single',
  'dependent_count' => NULL,
  'annual_income' => NULL,
  'City' => NULL,
  'phone_number' => NULL,
  'Status' => 'ACTIVE',
  'created_at' => '2024-07-29 01:42:50',
  'updated_at' => '2024-07-29 02:03:37',
  'collateral_manager_id' => 23,
  'identificationType' => 'Voter-ID',
  'identificationNo' => 'Voluptas et a qui co',
  'region' => '11',
  'district' => NULL,
  'ward' => NULL,
  'branch' => 25,
  'process' => '14',
  'step' => '3',
  'xx' => NULL,
),
            array (
  'id' => 25,
  'first_name' => 'Nostrum',
  'last_name' => 'Aut',
  'date_of_birth' => '1995-04-10',
  'gender' => 'Male',
  'contact_number' => NULL,
  'email' => 'simisor@mailinator.com',
  'address' => 'Et sint molestias mo',
  'occupation' => NULL,
  'education_level' => NULL,
  'marital_status' => 'Divorced',
  'dependent_count' => NULL,
  'annual_income' => NULL,
  'City' => NULL,
  'phone_number' => NULL,
  'Status' => 'PENDING',
  'created_at' => '2024-07-29 06:54:30',
  'updated_at' => '2024-07-29 06:54:30',
  'collateral_manager_id' => 23,
  'identificationType' => 'NIDA',
  'identificationNo' => 'Perspiciatis volupt',
  'region' => '7',
  'district' => '38',
  'ward' => '2994',
  'branch' => 25,
  'process' => '14',
  'step' => '2',
  'xx' => NULL,
),
            array (
  'id' => 26,
  'first_name' => 'Alias ',
  'last_name' => 'Architecto',
  'date_of_birth' => '2015-01-28',
  'gender' => 'Male',
  'contact_number' => NULL,
  'email' => 'ducozogyci@mailinator.com',
  'address' => 'Quisquam deserunt se',
  'occupation' => NULL,
  'education_level' => NULL,
  'marital_status' => 'Widowed',
  'dependent_count' => NULL,
  'annual_income' => NULL,
  'City' => NULL,
  'phone_number' => NULL,
  'Status' => 'ACTIVE',
  'created_at' => '2024-07-29 06:56:17',
  'updated_at' => '2024-07-29 07:32:05',
  'collateral_manager_id' => 23,
  'identificationType' => 'NIDA',
  'identificationNo' => 'Do quis excepturi qu',
  'region' => '15',
  'district' => '100',
  'ward' => '866',
  'branch' => 25,
  'process' => '14',
  'step' => '3',
  'xx' => NULL,
)
        ]);
    }
}