<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InstitutionsSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('institutions')->insert([
            array (
  'id' => 1,
  'institution_id' => NULL,
  'name' => 'WAZAWA',
  'region' => 'DAR ES SALAAM ',
  'wilaya' => 'KINONDONI',
  'phone_number' => NULL,
  'email' => NULL,
  'institution_status' => NULL,
  'imgUrl' => NULL,
  'admin' => NULL,
  'available_shares' => 400,
  'registration_fees' => 10000.0,
  'min_shares' => 10,
  'initial_shares' => NULL,
  'temp_shares_holding_account' => NULL,
  'value_per_share' => NULL,
  'selected' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
  'inactivity' => 24,
  'allocated_shares' => 500,
  'admin_email' => '',
  'manager_email' => '',
  'tin_number' => '',
  'tcdc_form' => '',
  'microfinance_license' => '',
  'status' => '',
  'notes' => NULL,
  'manager_image_url' => NULL,
  'manager_full_name' => NULL,
),
            array (
  'id' => 2,
  'institution_id' => NULL,
  'name' => NULL,
  'region' => NULL,
  'wilaya' => NULL,
  'phone_number' => '1234567891',
  'email' => NULL,
  'institution_status' => NULL,
  'imgUrl' => NULL,
  'admin' => NULL,
  'available_shares' => NULL,
  'registration_fees' => NULL,
  'min_shares' => NULL,
  'initial_shares' => NULL,
  'temp_shares_holding_account' => NULL,
  'value_per_share' => NULL,
  'selected' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
  'inactivity' => NULL,
  'allocated_shares' => NULL,
  'admin_email' => 'percyegno@gmail.com',
  'manager_email' => 'joa@gmail.com',
  'tin_number' => 'Tin2123344',
  'tcdc_form' => NULL,
  'microfinance_license' => NULL,
  'status' => '',
  'notes' => NULL,
  'manager_image_url' => NULL,
  'manager_full_name' => NULL,
),
            array (
  'id' => 3,
  'institution_id' => NULL,
  'name' => NULL,
  'region' => NULL,
  'wilaya' => NULL,
  'phone_number' => '1234567891',
  'email' => NULL,
  'institution_status' => NULL,
  'imgUrl' => NULL,
  'admin' => NULL,
  'available_shares' => NULL,
  'registration_fees' => NULL,
  'min_shares' => NULL,
  'initial_shares' => NULL,
  'temp_shares_holding_account' => NULL,
  'value_per_share' => NULL,
  'selected' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
  'inactivity' => NULL,
  'allocated_shares' => NULL,
  'admin_email' => 'percyegno@gmail.com',
  'manager_email' => 'joa@gmail.com',
  'tin_number' => 'Tin2123344',
  'tcdc_form' => NULL,
  'microfinance_license' => NULL,
  'status' => '',
  'notes' => NULL,
  'manager_image_url' => NULL,
  'manager_full_name' => NULL,
),
            array (
  'id' => 4,
  'institution_id' => NULL,
  'name' => NULL,
  'region' => NULL,
  'wilaya' => NULL,
  'phone_number' => '1234567891',
  'email' => NULL,
  'institution_status' => NULL,
  'imgUrl' => NULL,
  'admin' => NULL,
  'available_shares' => NULL,
  'registration_fees' => NULL,
  'min_shares' => NULL,
  'initial_shares' => NULL,
  'temp_shares_holding_account' => NULL,
  'value_per_share' => NULL,
  'selected' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
  'inactivity' => NULL,
  'allocated_shares' => NULL,
  'admin_email' => 'percyegno@gmail.com',
  'manager_email' => 'joa@gmail.com',
  'tin_number' => 'Tin2123344',
  'tcdc_form' => NULL,
  'microfinance_license' => NULL,
  'status' => '',
  'notes' => NULL,
  'manager_image_url' => NULL,
  'manager_full_name' => NULL,
),
            array (
  'id' => 5,
  'institution_id' => NULL,
  'name' => NULL,
  'region' => NULL,
  'wilaya' => NULL,
  'phone_number' => '1234567891',
  'email' => NULL,
  'institution_status' => NULL,
  'imgUrl' => NULL,
  'admin' => NULL,
  'available_shares' => NULL,
  'registration_fees' => NULL,
  'min_shares' => NULL,
  'initial_shares' => NULL,
  'temp_shares_holding_account' => NULL,
  'value_per_share' => NULL,
  'selected' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
  'inactivity' => NULL,
  'allocated_shares' => NULL,
  'admin_email' => 'percyegno@gmail.com',
  'manager_email' => 'joa@gmail.com',
  'tin_number' => 'Tin2123344',
  'tcdc_form' => NULL,
  'microfinance_license' => NULL,
  'status' => '',
  'notes' => NULL,
  'manager_image_url' => NULL,
  'manager_full_name' => NULL,
),
            array (
  'id' => 6,
  'institution_id' => NULL,
  'name' => NULL,
  'region' => NULL,
  'wilaya' => NULL,
  'phone_number' => '+2551234567891',
  'email' => NULL,
  'institution_status' => NULL,
  'imgUrl' => NULL,
  'admin' => NULL,
  'available_shares' => NULL,
  'registration_fees' => NULL,
  'min_shares' => NULL,
  'initial_shares' => NULL,
  'temp_shares_holding_account' => NULL,
  'value_per_share' => NULL,
  'selected' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
  'inactivity' => NULL,
  'allocated_shares' => NULL,
  'admin_email' => 'percyegno@gmail.com',
  'manager_email' => 'joa@gmail.com',
  'tin_number' => 'Tin2123344',
  'tcdc_form' => 'Saccoss-request/1691560731_report_template.pdf',
  'microfinance_license' => 'Saccoss-request/1691560731_ACCOUNTING AND FINANCE MODULE.docx',
  'status' => 'PENDING',
  'notes' => NULL,
  'manager_image_url' => NULL,
  'manager_full_name' => NULL,
),
            array (
  'id' => 8,
  'institution_id' => '8',
  'name' => 'MIKOCHENI INSTITUTE',
  'region' => 'DAR ES SALAAM',
  'wilaya' => 'ILALA',
  'phone_number' => '+2551234567891',
  'email' => NULL,
  'institution_status' => NULL,
  'imgUrl' => 'InstitutionLogo/mikocheni.png',
  'admin' => NULL,
  'available_shares' => NULL,
  'registration_fees' => 10000.0,
  'min_shares' => 4,
  'initial_shares' => NULL,
  'temp_shares_holding_account' => NULL,
  'value_per_share' => '20000',
  'selected' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
  'inactivity' => NULL,
  'allocated_shares' => NULL,
  'admin_email' => 'percyegno@gmail.com',
  'manager_email' => 'joa@gmail.com',
  'tin_number' => 'Tin2123344',
  'tcdc_form' => 'Saccoss-request/1691572216_ACCOUNTING AND FINANCE MODULE.docx',
  'microfinance_license' => 'Saccoss-request/1691572216_BUSINESS REQUIREMT SPECIFICATION FOR CSS-SACCOS SIDE-DAY THREE (1).docx',
  'status' => 'PENDING',
  'notes' => 'Welcome to Mikocheni Institute Microfinance, where financial empowerment meets personalized service. As a distinguished institution in the heart of Dar es Salaam, we are dedicated to transforming lives through accessible and innovative microfinance solutions',
  'manager_image_url' => NULL,
  'manager_full_name' => 'JOHN JACOB KINGAZI',
)
        ]);
    }
}