<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PledgesSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pledges')->insert([
            array (
  'id' => 1,
  'client_id' => '1',
  'application_id' => '5',
  'commodity_id' => '2',
  'loan_id' => NULL,
  'kilos' => '10000',
  'amount' => NULL,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 2,
  'client_id' => '1',
  'application_id' => '6',
  'commodity_id' => '2',
  'loan_id' => NULL,
  'kilos' => '100000',
  'amount' => NULL,
  'Status' => 'COLLATERAL RELEASED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 3,
  'client_id' => '1',
  'application_id' => '7',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '800',
  'amount' => 2400000.0,
  'Status' => 'COLLATERAL RELEASED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 4,
  'client_id' => '1',
  'application_id' => '7',
  'commodity_id' => '2',
  'loan_id' => NULL,
  'kilos' => '7000',
  'amount' => 12600000.0,
  'Status' => 'COLLATERAL RELEASED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 5,
  'client_id' => '1',
  'application_id' => '8',
  'commodity_id' => '2',
  'loan_id' => NULL,
  'kilos' => '7000',
  'amount' => 12600000.0,
  'Status' => 'COLLATERAL RELEASED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 6,
  'client_id' => '1',
  'application_id' => '8',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '8000',
  'amount' => 24000000.0,
  'Status' => 'COLLATERAL RELEASED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 7,
  'client_id' => '1',
  'application_id' => '9',
  'commodity_id' => '2',
  'loan_id' => NULL,
  'kilos' => '1000',
  'amount' => 1800000.0,
  'Status' => 'COLLATERAL RELEASED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 8,
  'client_id' => '1',
  'application_id' => '9',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '1000',
  'amount' => 3000000.0,
  'Status' => 'COLLATERAL RELEASED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 9,
  'client_id' => '1',
  'application_id' => '10',
  'commodity_id' => '2',
  'loan_id' => NULL,
  'kilos' => '1000',
  'amount' => 1800000.0,
  'Status' => 'COLLATERAL RELEASED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 10,
  'client_id' => '1',
  'application_id' => '10',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '1000',
  'amount' => 3000000.0,
  'Status' => 'COLLATERAL RELEASED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 11,
  'client_id' => '1',
  'application_id' => '11',
  'commodity_id' => '2',
  'loan_id' => NULL,
  'kilos' => '1000',
  'amount' => 1800000.0,
  'Status' => 'COLLATERAL RELEASED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 12,
  'client_id' => '1',
  'application_id' => '11',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '1000',
  'amount' => 3000000.0,
  'Status' => 'COLLATERAL RELEASED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 13,
  'client_id' => '1',
  'application_id' => '13',
  'commodity_id' => '2',
  'loan_id' => NULL,
  'kilos' => '1000',
  'amount' => 1800000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 14,
  'client_id' => '1',
  'application_id' => '13',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '1000',
  'amount' => 3000000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 15,
  'client_id' => '1',
  'application_id' => '14',
  'commodity_id' => '2',
  'loan_id' => NULL,
  'kilos' => '1000',
  'amount' => 1800000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 16,
  'client_id' => '1',
  'application_id' => '14',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '1000',
  'amount' => 3000000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 17,
  'client_id' => '1',
  'application_id' => '15',
  'commodity_id' => '2',
  'loan_id' => NULL,
  'kilos' => '1000',
  'amount' => 1800000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 18,
  'client_id' => '1',
  'application_id' => '15',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '1000',
  'amount' => 3000000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 19,
  'client_id' => '1',
  'application_id' => '16',
  'commodity_id' => '2',
  'loan_id' => NULL,
  'kilos' => '1000',
  'amount' => 1800000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 20,
  'client_id' => '1',
  'application_id' => '16',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '1000',
  'amount' => 3000000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 21,
  'client_id' => '1',
  'application_id' => '17',
  'commodity_id' => '2',
  'loan_id' => NULL,
  'kilos' => '66',
  'amount' => 118800.0,
  'Status' => 'COLLATERAL RELEASED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 22,
  'client_id' => '1',
  'application_id' => '17',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '88',
  'amount' => 264000.0,
  'Status' => 'COLLATERAL RELEASED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 23,
  'client_id' => '2',
  'application_id' => '18',
  'commodity_id' => '4',
  'loan_id' => NULL,
  'kilos' => '20000',
  'amount' => 120000000.0,
  'Status' => 'COLLATERAL RELEASED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 24,
  'client_id' => '3',
  'application_id' => '19',
  'commodity_id' => '5',
  'loan_id' => NULL,
  'kilos' => '50',
  'amount' => 290000.0,
  'Status' => 'COLLATERAL RELEASED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 25,
  'client_id' => '3',
  'application_id' => '19',
  'commodity_id' => '2',
  'loan_id' => NULL,
  'kilos' => '30000',
  'amount' => 54000000.0,
  'Status' => 'COLLATERAL RELEASED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 26,
  'client_id' => '1',
  'application_id' => '20',
  'commodity_id' => '2',
  'loan_id' => NULL,
  'kilos' => '200000000',
  'amount' => 360000000000.0,
  'Status' => 'COLLATERAL RELEASED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 27,
  'client_id' => '2',
  'application_id' => '21',
  'commodity_id' => '7',
  'loan_id' => NULL,
  'kilos' => '45000',
  'amount' => 81000000.0,
  'Status' => 'COLLATERAL RELEASED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 28,
  'client_id' => '1',
  'application_id' => '22',
  'commodity_id' => '2',
  'loan_id' => NULL,
  'kilos' => '1',
  'amount' => 1800.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 29,
  'client_id' => '1',
  'application_id' => '22',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '150000',
  'amount' => 675000000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 30,
  'client_id' => '1',
  'application_id' => '22',
  'commodity_id' => '5',
  'loan_id' => NULL,
  'kilos' => '8000',
  'amount' => 46400000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 31,
  'client_id' => '1',
  'application_id' => '22',
  'commodity_id' => '9',
  'loan_id' => NULL,
  'kilos' => '300000',
  'amount' => 720000000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 32,
  'client_id' => '2',
  'application_id' => '23',
  'commodity_id' => '10',
  'loan_id' => NULL,
  'kilos' => '300000',
  'amount' => 210000000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 33,
  'client_id' => '2',
  'application_id' => '24',
  'commodity_id' => '7',
  'loan_id' => NULL,
  'kilos' => '20',
  'amount' => 36000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 34,
  'client_id' => '2',
  'application_id' => '24',
  'commodity_id' => '10',
  'loan_id' => NULL,
  'kilos' => '40',
  'amount' => 28000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 35,
  'client_id' => '1',
  'application_id' => '25',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '70000',
  'amount' => 315000000.0,
  'Status' => 'COLLATERAL RELEASED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 36,
  'client_id' => '1',
  'application_id' => '25',
  'commodity_id' => '5',
  'loan_id' => NULL,
  'kilos' => '1000',
  'amount' => 5800000.0,
  'Status' => 'COLLATERAL RELEASED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 37,
  'client_id' => '1',
  'application_id' => '27',
  'commodity_id' => '2',
  'loan_id' => NULL,
  'kilos' => '56',
  'amount' => 436800.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 38,
  'client_id' => '1',
  'application_id' => '27',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '67',
  'amount' => 529233.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 39,
  'client_id' => '1',
  'application_id' => '27',
  'commodity_id' => '5',
  'loan_id' => NULL,
  'kilos' => '780',
  'amount' => 4524000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 40,
  'client_id' => '1',
  'application_id' => '27',
  'commodity_id' => '9',
  'loan_id' => NULL,
  'kilos' => '2000',
  'amount' => 4800000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 41,
  'client_id' => '9',
  'application_id' => '28',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '54',
  'amount' => 426546.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 42,
  'client_id' => '9',
  'application_id' => '28',
  'commodity_id' => '4',
  'loan_id' => NULL,
  'kilos' => '1000',
  'amount' => 6000000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 43,
  'client_id' => '9',
  'application_id' => '28',
  'commodity_id' => '12',
  'loan_id' => NULL,
  'kilos' => '200',
  'amount' => 560000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 44,
  'client_id' => '9',
  'application_id' => '29',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '400',
  'amount' => 480000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 45,
  'client_id' => '9',
  'application_id' => '29',
  'commodity_id' => '4',
  'loan_id' => NULL,
  'kilos' => '1000',
  'amount' => 6000000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 46,
  'client_id' => '9',
  'application_id' => '29',
  'commodity_id' => '12',
  'loan_id' => NULL,
  'kilos' => '600',
  'amount' => 1680000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 47,
  'client_id' => '9',
  'application_id' => '30',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '77',
  'amount' => 92400.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 48,
  'client_id' => '9',
  'application_id' => '30',
  'commodity_id' => '4',
  'loan_id' => NULL,
  'kilos' => '97',
  'amount' => 582000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 49,
  'client_id' => '9',
  'application_id' => '30',
  'commodity_id' => '12',
  'loan_id' => NULL,
  'kilos' => '90',
  'amount' => 252000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 50,
  'client_id' => '9',
  'application_id' => '31',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '56',
  'amount' => 67200.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 51,
  'client_id' => '9',
  'application_id' => '31',
  'commodity_id' => '4',
  'loan_id' => NULL,
  'kilos' => '456',
  'amount' => 2736000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 52,
  'client_id' => '9',
  'application_id' => '31',
  'commodity_id' => '12',
  'loan_id' => NULL,
  'kilos' => '77',
  'amount' => 215600.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 53,
  'client_id' => '9',
  'application_id' => '32',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '78',
  'amount' => 93600.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 54,
  'client_id' => '9',
  'application_id' => '32',
  'commodity_id' => '4',
  'loan_id' => NULL,
  'kilos' => '45',
  'amount' => 270000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 55,
  'client_id' => '9',
  'application_id' => '32',
  'commodity_id' => '12',
  'loan_id' => NULL,
  'kilos' => '90',
  'amount' => 252000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 56,
  'client_id' => '9',
  'application_id' => '33',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '500',
  'amount' => 600000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 57,
  'client_id' => '9',
  'application_id' => '33',
  'commodity_id' => '4',
  'loan_id' => NULL,
  'kilos' => '1000',
  'amount' => 6000000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 58,
  'client_id' => '9',
  'application_id' => '33',
  'commodity_id' => '12',
  'loan_id' => NULL,
  'kilos' => '500',
  'amount' => 1400000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 59,
  'client_id' => '9',
  'application_id' => '34',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '400',
  'amount' => 480000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 60,
  'client_id' => '9',
  'application_id' => '34',
  'commodity_id' => '4',
  'loan_id' => NULL,
  'kilos' => '789',
  'amount' => 4734000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 61,
  'client_id' => '9',
  'application_id' => '34',
  'commodity_id' => '12',
  'loan_id' => NULL,
  'kilos' => '56',
  'amount' => 156800.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 62,
  'client_id' => '18',
  'application_id' => '35',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '7700',
  'amount' => 9240000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 63,
  'client_id' => '18',
  'application_id' => '35',
  'commodity_id' => '2',
  'loan_id' => NULL,
  'kilos' => '900',
  'amount' => 7200000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 64,
  'client_id' => '19',
  'application_id' => '36',
  'commodity_id' => '3',
  'loan_id' => NULL,
  'kilos' => '300',
  'amount' => 270000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 65,
  'client_id' => '18',
  'application_id' => '37',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '400',
  'amount' => 480000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 66,
  'client_id' => '18',
  'application_id' => '37',
  'commodity_id' => '2',
  'loan_id' => NULL,
  'kilos' => '700',
  'amount' => 5600000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 67,
  'client_id' => '18',
  'application_id' => '38',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '400',
  'amount' => 480000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 68,
  'client_id' => '18',
  'application_id' => '38',
  'commodity_id' => '2',
  'loan_id' => NULL,
  'kilos' => '700',
  'amount' => 5600000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 69,
  'client_id' => '18',
  'application_id' => '39',
  'commodity_id' => '1',
  'loan_id' => NULL,
  'kilos' => '300',
  'amount' => 360000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 70,
  'client_id' => '18',
  'application_id' => '39',
  'commodity_id' => '2',
  'loan_id' => NULL,
  'kilos' => '500',
  'amount' => 4000000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 71,
  'client_id' => '18',
  'application_id' => '39',
  'commodity_id' => '11',
  'loan_id' => NULL,
  'kilos' => '600',
  'amount' => 1380000.0,
  'Status' => 'PLEDGED',
  'interest' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
)
        ]);
    }
}