<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubMenusSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sub_menus')->insert([
            array (
  'id' => 1,
  'system_id' => 1,
  'menu_id' => 13,
  'sub_menu_name' => 'Can Register Stocks',
  'user_action' => 'Can Register Stocks',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 2,
  'system_id' => 1,
  'menu_id' => 13,
  'sub_menu_name' => 'Can View Releases Stocks Report',
  'user_action' => 'Can View Releases Stocks Report',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 3,
  'system_id' => 1,
  'menu_id' => 13,
  'sub_menu_name' => 'Can Views Stock Reports',
  'user_action' => 'Can Views Stock Reports',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 4,
  'system_id' => 1,
  'menu_id' => 2,
  'sub_menu_name' => 'Can View Farmer Details',
  'user_action' => 'Can View Farmer Details',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 5,
  'system_id' => 1,
  'menu_id' => 13,
  'sub_menu_name' => 'Can View Collateral Releases',
  'user_action' => 'Can View Collateral Releases',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 6,
  'system_id' => 1,
  'menu_id' => 9,
  'sub_menu_name' => 'Can Create System User',
  'user_action' => 'Can Create System User',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 7,
  'system_id' => 1,
  'menu_id' => 9,
  'sub_menu_name' => 'Can Update System User',
  'user_action' => 'Can Update System User',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 8,
  'system_id' => 1,
  'menu_id' => 9,
  'sub_menu_name' => 'Can Delete System User',
  'user_action' => 'Can Delete System User',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 9,
  'system_id' => 1,
  'menu_id' => 9,
  'sub_menu_name' => 'Can Manages Roles And System Permissions',
  'user_action' => 'Can Manages Roles And System Permissions',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 10,
  'system_id' => 1,
  'menu_id' => 10,
  'sub_menu_name' => 'Can Create Collateral Managers',
  'user_action' => 'Can Create Collateral Managers',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 11,
  'system_id' => 1,
  'menu_id' => 10,
  'sub_menu_name' => 'Can Update Collateral Managers',
  'user_action' => 'Can Update Collateral Managers',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 12,
  'system_id' => 1,
  'menu_id' => 10,
  'sub_menu_name' => 'Can Delete Collateral Managers',
  'user_action' => 'Can Delete Collateral Managers',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 13,
  'system_id' => 1,
  'menu_id' => 13,
  'sub_menu_name' => 'Can Request Releases Stocks',
  'user_action' => 'Can Request Releases Stocks',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 14,
  'system_id' => 1,
  'menu_id' => 2,
  'sub_menu_name' => 'Can Create Farmer',
  'user_action' => 'Can Create Farmer',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 15,
  'system_id' => 1,
  'menu_id' => 2,
  'sub_menu_name' => 'Can Update Farmer',
  'user_action' => 'Can Update Farmer',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 16,
  'system_id' => 1,
  'menu_id' => 2,
  'sub_menu_name' => 'Can Delete Farmer',
  'user_action' => 'Can Delete Farmer',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 17,
  'system_id' => 1,
  'menu_id' => 10,
  'sub_menu_name' => 'Can View Collateral Managers',
  'user_action' => 'Can View Collateral Managers',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 18,
  'system_id' => 1,
  'menu_id' => 11,
  'sub_menu_name' => 'Can Create Commodity',
  'user_action' => 'Can Create Commodity',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 19,
  'system_id' => 1,
  'menu_id' => 11,
  'sub_menu_name' => 'Can Update Commodity Prices',
  'user_action' => 'Can Update Commodity Prices',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 20,
  'system_id' => 1,
  'menu_id' => 11,
  'sub_menu_name' => 'Can Delete Commodity',
  'user_action' => 'Can Delete Commodity',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 21,
  'system_id' => 1,
  'menu_id' => 11,
  'sub_menu_name' => 'Can View Commodity',
  'user_action' => 'Can View Commodity',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 22,
  'system_id' => 1,
  'menu_id' => 12,
  'sub_menu_name' => 'Can Approves Releases Stocks',
  'user_action' => 'Can Approves Releases Stocks',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 23,
  'system_id' => 1,
  'menu_id' => 12,
  'sub_menu_name' => 'Can Rejects Release Requests',
  'user_action' => 'Can Rejects Release Requests',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 24,
  'system_id' => 1,
  'menu_id' => 13,
  'sub_menu_name' => 'Can Releases Stocks',
  'user_action' => 'Can Releases Stocks',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
),
            array (
  'id' => 25,
  'system_id' => 1,
  'menu_id' => 13,
  'sub_menu_name' => 'Notifications',
  'user_action' => 'Notifications',
  'position' => 35,
  'created_at' => NULL,
  'updated_at' => NULL,
)
        ]);
    }
}