<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubProductsSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sub_products')->insert([
            array (
  'id' => 1,
  'product_name' => '',
  'product_id' => 11,
  'default_status' => NULL,
  'sub_product_name' => 'HISA ZA MALENGO',
  'sub_product_id' => '1178',
  'sub_product_status' => 0,
  'currency' => '1',
  'deposit' => NULL,
  'deposit_charge' => NULL,
  'deposit_charge_min_value' => NULL,
  'deposit_charge_max_value' => NULL,
  'withdraw' => NULL,
  'withdraw_charge' => NULL,
  'withdraw_charge_min_value' => NULL,
  'withdraw_charge_max_value' => NULL,
  'interest_value' => NULL,
  'interest_tenure' => NULL,
  'maintenance_fees' => NULL,
  'maintenance_fees_value' => NULL,
  'profit_account' => 'FAMILY SAVING',
  'inactivity' => '18',
  'create_during_registration' => 1,
  'activated_by_lower_limit' => 1,
  'requires_approval' => 1,
  'generate_atm_card_profile' => 1,
  'allow_statement_generation' => 1,
  'send_notifications' => 1,
  'require_image_member' => 1,
  'require_image_id' => 0,
  'require_mobile_number' => 0,
  'generate_mobile_profile' => 1,
  'notes' => 'HISA ZA MALENGO',
  'interest' => NULL,
  'ledger_fees' => NULL,
  'ledger_fees_value' => NULL,
  'total_shares' => 500000,
  'shares_per_member' => 10,
  'nominal_price' => 2000.0,
  'shares_allocated' => NULL,
  'available_shares' => 5000.0,
  'created_at' => '2023-07-02 10:46:53',
  'updated_at' => '2023-08-17 15:55:08',
),
            array (
  'id' => 8,
  'product_name' => '',
  'product_id' => 12,
  'default_status' => NULL,
  'sub_product_name' => 'DEMO SAVING',
  'sub_product_id' => '1266',
  'sub_product_status' => 0,
  'currency' => '1',
  'deposit' => 0,
  'deposit_charge' => 500.0,
  'deposit_charge_min_value' => NULL,
  'deposit_charge_max_value' => NULL,
  'withdraw' => 0,
  'withdraw_charge' => 1.0,
  'withdraw_charge_min_value' => NULL,
  'withdraw_charge_max_value' => NULL,
  'interest_value' => 6.0,
  'interest_tenure' => 12.0,
  'maintenance_fees' => NULL,
  'maintenance_fees_value' => NULL,
  'profit_account' => NULL,
  'inactivity' => NULL,
  'create_during_registration' => NULL,
  'activated_by_lower_limit' => NULL,
  'requires_approval' => NULL,
  'generate_atm_card_profile' => NULL,
  'allow_statement_generation' => NULL,
  'send_notifications' => NULL,
  'require_image_member' => NULL,
  'require_image_id' => NULL,
  'require_mobile_number' => NULL,
  'generate_mobile_profile' => NULL,
  'notes' => 'PRODUCT',
  'interest' => 1,
  'ledger_fees' => NULL,
  'ledger_fees_value' => NULL,
  'total_shares' => NULL,
  'shares_per_member' => NULL,
  'nominal_price' => NULL,
  'shares_allocated' => NULL,
  'available_shares' => NULL,
  'created_at' => '2023-08-08 12:05:29',
  'updated_at' => '2023-08-08 12:05:29',
),
            array (
  'id' => 9,
  'product_name' => '',
  'product_id' => 13,
  'default_status' => NULL,
  'sub_product_name' => 'DEPO TEST',
  'sub_product_id' => '1367',
  'sub_product_status' => 0,
  'currency' => '1',
  'deposit' => NULL,
  'deposit_charge' => NULL,
  'deposit_charge_min_value' => NULL,
  'deposit_charge_max_value' => NULL,
  'withdraw' => NULL,
  'withdraw_charge' => NULL,
  'withdraw_charge_min_value' => NULL,
  'withdraw_charge_max_value' => NULL,
  'interest_value' => NULL,
  'interest_tenure' => NULL,
  'maintenance_fees' => NULL,
  'maintenance_fees_value' => NULL,
  'profit_account' => NULL,
  'inactivity' => NULL,
  'create_during_registration' => NULL,
  'activated_by_lower_limit' => NULL,
  'requires_approval' => NULL,
  'generate_atm_card_profile' => NULL,
  'allow_statement_generation' => NULL,
  'send_notifications' => NULL,
  'require_image_member' => NULL,
  'require_image_id' => NULL,
  'require_mobile_number' => NULL,
  'generate_mobile_profile' => NULL,
  'notes' => NULL,
  'interest' => NULL,
  'ledger_fees' => NULL,
  'ledger_fees_value' => NULL,
  'total_shares' => NULL,
  'shares_per_member' => NULL,
  'nominal_price' => NULL,
  'shares_allocated' => NULL,
  'available_shares' => NULL,
  'created_at' => '2023-08-08 12:21:38',
  'updated_at' => '2023-08-08 12:21:38',
)
        ]);
    }
}