<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateTempPermissionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('temp_permissions', function (Blueprint $table) {
            $table->id();
            $table->string('user_id')->nullable();
            $table->string('t1')->nullable();
            $table->string('t2')->nullable();
            $table->string('t3')->nullable();
            $table->string('t4')->nullable();
            $table->string('t5')->nullable();
            $table->string('t6')->nullable();
            $table->string('t7')->nullable();
            $table->string('t8')->nullable();
            $table->string('t9')->nullable();
            $table->string('t10')->nullable();
            $table->string('t11')->nullable();
            $table->string('t12')->nullable();
            $table->string('t13')->nullable();
            $table->string('t14')->nullable();
            $table->string('t15')->nullable();
            $table->string('t16')->nullable();
            $table->string('t17')->nullable();
            $table->string('t18')->nullable();
            $table->string('t19')->nullable();
            $table->string('t20')->nullable();
            $table->string('t21')->nullable();
            $table->string('t22')->nullable();
            $table->string('t23')->nullable();
            $table->string('t24')->nullable();
            $table->string('t25')->nullable();
            $table->string('t26')->nullable();
            $table->string('t27')->nullable();
            $table->string('t28')->nullable();
            $table->string('t29')->nullable();
            $table->string('t30')->nullable();
            $table->string('t31')->nullable();
            $table->string('t32')->nullable();
            $table->string('t33')->nullable();
            $table->string('t34')->nullable();
            $table->string('t35')->nullable();
            $table->string('t36')->nullable();
            $table->string('t37')->nullable();
            $table->string('t38')->nullable();
            $table->string('t39')->nullable();
            $table->string('t40')->nullable();
            $table->string('t41')->nullable();
            $table->string('t42')->nullable();
            $table->string('t43')->nullable();
            $table->string('t44')->nullable();
            $table->string('t45')->nullable();
            $table->string('t46')->nullable();
            $table->string('t47')->nullable();
            $table->string('t48')->nullable();
            $table->string('t49')->nullable();
            $table->string('t50')->nullable();
            $table->string('t51')->nullable();
            $table->string('t52')->nullable();
            $table->string('t53')->nullable();
            $table->string('t54')->nullable();
            $table->string('t55')->nullable();
            $table->string('t56')->nullable();
            $table->string('t57')->nullable();
            $table->string('t58')->nullable();
            $table->string('t59')->nullable();
            $table->string('t60')->nullable();
            $table->string('t61')->nullable();
            $table->string('t62')->nullable();
            $table->string('t63')->nullable();
            $table->string('t64')->nullable();
            $table->string('t65')->nullable();
            $table->string('t66')->nullable();
            $table->string('t67')->nullable();
            $table->string('t68')->nullable();
            $table->string('t69')->nullable();
            $table->string('t70')->nullable();
            $table->string('t71')->nullable();
            $table->string('t72')->nullable();
            $table->string('t73')->nullable();
            $table->string('t74')->nullable();
            $table->string('t75')->nullable();
            $table->string('t76')->nullable();
            $table->string('t77')->nullable();
            $table->string('t78')->nullable();
            $table->string('t79')->nullable();
            $table->string('t80')->nullable();
            $table->string('t81')->nullable();
            $table->string('t82')->nullable();
            $table->string('t83')->nullable();
            $table->string('t84')->nullable();
            $table->string('t85')->nullable();
            $table->string('t86')->nullable();
            $table->string('t87')->nullable();
            $table->string('t88')->nullable();
            $table->string('t89')->nullable();
            $table->string('t90')->nullable();
            $table->string('t91')->nullable();
            $table->string('t92')->nullable();
            $table->string('t93')->nullable();
            $table->string('t94')->nullable();
            $table->string('t95')->nullable();
            $table->string('t96')->nullable();
            $table->string('t97')->nullable();
            $table->string('t98')->nullable();
            $table->string('t99')->nullable();
            $table->string('t100')->nullable();
            $table->string('t101')->nullable();
            $table->string('t102')->nullable();
            $table->string('t103')->nullable();
            $table->string('t104')->nullable();
            $table->string('t105')->nullable();
            $table->string('t106')->nullable();
            $table->string('t107')->nullable();
            $table->string('t108')->nullable();
            $table->string('t109')->nullable();
            $table->string('t110')->nullable();
            $table->string('t111')->nullable();
            $table->string('t112')->nullable();
            $table->string('t113')->nullable();
            $table->string('t114')->nullable();
            $table->string('t115')->nullable();
            $table->string('t116')->nullable();
            $table->string('t117')->nullable();
            $table->string('t118')->nullable();
            $table->string('t119')->nullable();
            $table->string('t120')->nullable();
            $table->string('t121')->nullable();
            $table->string('t122')->nullable();
            $table->string('t123')->nullable();
            $table->string('t124')->nullable();
            $table->string('t125')->nullable();
            $table->string('t126')->nullable();
            $table->string('t127')->nullable();
            $table->string('t128')->nullable();
            $table->string('t129')->nullable();
            $table->string('t130')->nullable();
            $table->string('t131')->nullable();
            $table->string('t132')->nullable();
            $table->string('t133')->nullable();
            $table->string('t134')->nullable();
            $table->string('t135')->nullable();
            $table->string('t136')->nullable();
            $table->string('t137')->nullable();
            $table->string('t138')->nullable();
            $table->string('t139')->nullable();
            $table->string('t140')->nullable();
            $table->string('t141')->nullable();
            $table->string('t142')->nullable();
            $table->string('t143')->nullable();
            $table->string('t144')->nullable();
            $table->string('t145')->nullable();
            $table->string('t146')->nullable();
            $table->string('t147')->nullable();
            $table->string('t148')->nullable();
            $table->string('t149')->nullable();
            $table->string('t150')->nullable();
            $table->string('t151')->nullable();
            $table->string('t152')->nullable();
            $table->string('t153')->nullable();
            $table->string('t154')->nullable();
            $table->string('t155')->nullable();
            $table->string('t156')->nullable();
            $table->string('t157')->nullable();
            $table->string('t158')->nullable();
            $table->string('t159')->nullable();
            $table->string('t160')->nullable();
            $table->string('t161')->nullable();
            $table->string('t162')->nullable();
            $table->string('t163')->nullable();
            $table->string('t164')->nullable();
            $table->string('t165')->nullable();
            $table->string('t166')->nullable();
            $table->string('t167')->nullable();
            $table->string('t168')->nullable();
            $table->string('t169')->nullable();
            $table->string('t170')->nullable();
            $table->string('t171')->nullable();
            $table->string('t172')->nullable();
            $table->string('t173')->nullable();
            $table->string('t174')->nullable();
            $table->string('t175')->nullable();
            $table->string('t176')->nullable();
            $table->string('t177')->nullable();
            $table->string('t178')->nullable();
            $table->string('t179')->nullable();
            $table->string('t180')->nullable();
            $table->string('t181')->nullable();
            $table->string('t182')->nullable();
            $table->string('t183')->nullable();
            $table->string('t184')->nullable();
            $table->string('t185')->nullable();
            $table->string('t186')->nullable();
            $table->string('t187')->nullable();
            $table->string('t188')->nullable();
            $table->string('t189')->nullable();
            $table->string('t190')->nullable();
            $table->string('t191')->nullable();
            $table->string('t192')->nullable();
            $table->string('t193')->nullable();
            $table->string('t194')->nullable();
            $table->string('t195')->nullable();
            $table->string('t196')->nullable();
            $table->string('t197')->nullable();
            $table->string('t198')->nullable();
            $table->string('t199')->nullable();
            $table->string('t200')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('temp_permissions');
    }
}